{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "ui-smartcamera",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-smartcamera-1.3.0.aar",
          "url": "ui-smartcamera-1.3.0.aar",
          "size": 603875,
          "sha512": "b47793ba5337ada0f50771ccb156fdab8573ff97e4cc9fc6af109aecc417d15ed0e9cc4091693d4a3ee945f5c07cea5a11dc4e983539afb7efdee27f4933dbc0",
          "sha256": "f788f6242a93ea94bc353b24009fbb4ddc604bf52d030551edbe2aff55c5f2b3",
          "sha1": "c0a71a6f5269f584b0404a4fb232e501477f6ce1",
          "md5": "13ffd745226642b062c40f9a6e6363f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-smartcamera-1.3.0.aar",
          "url": "ui-smartcamera-1.3.0.aar",
          "size": 603875,
          "sha512": "b47793ba5337ada0f50771ccb156fdab8573ff97e4cc9fc6af109aecc417d15ed0e9cc4091693d4a3ee945f5c07cea5a11dc4e983539afb7efdee27f4933dbc0",
          "sha256": "f788f6242a93ea94bc353b24009fbb4ddc604bf52d030551edbe2aff55c5f2b3",
          "sha1": "c0a71a6f5269f584b0404a4fb232e501477f6ce1",
          "md5": "13ffd745226642b062c40f9a6e6363f8"
        }
      ]
    }
  ]
}
