{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "calling-client",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "calling-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "calling-client-1.3.0.aar",
          "url": "calling-client-1.3.0.aar",
          "size": 11200,
          "sha512": "9d58e1c832363d7028127b5d428f45628ceb3c239d8795ed8cabc7a77f0e98322b416648042cda751136c87888363eb49f5db4ff30828fe1bb5a86e115882f83",
          "sha256": "3de8595ff599bb3d86042bb846811d6a8a83c5348b3317f5a2953363cd51d772",
          "sha1": "9abcbb42670714eb1c149af1c621db23f231d3a4",
          "md5": "a8d84bf3835f43dcbd0ebe861d33e371"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "calling-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "calling-client-1.3.0.aar",
          "url": "calling-client-1.3.0.aar",
          "size": 11200,
          "sha512": "9d58e1c832363d7028127b5d428f45628ceb3c239d8795ed8cabc7a77f0e98322b416648042cda751136c87888363eb49f5db4ff30828fe1bb5a86e115882f83",
          "sha256": "3de8595ff599bb3d86042bb846811d6a8a83c5348b3317f5a2953363cd51d772",
          "sha1": "9abcbb42670714eb1c149af1c621db23f231d3a4",
          "md5": "a8d84bf3835f43dcbd0ebe861d33e371"
        }
      ]
    }
  ]
}
