{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "assistantactions-ipc",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "assistantactions-ipc-1.1.1.aar",
          "url": "assistantactions-ipc-1.1.1.aar",
          "size": 16678,
          "sha512": "811c61a3b56418e037ec55d93061c6113eb213f650c4a9f2f735d2a390f6423e242b6574bca90907e8330add05555d19fe560922bfd56cf591ae349a8f3b53bd",
          "sha256": "329ed3e31fe81a8851b3523bbe44739852121ec2651af632a57f0aedbb53afec",
          "sha1": "36d370b7e6018d75b61c685f84cd1a152424042e",
          "md5": "dfd93773ef79ea7dee6e6fb4a4ce32f2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "assistantactions-ipc-1.1.1.aar",
          "url": "assistantactions-ipc-1.1.1.aar",
          "size": 16678,
          "sha512": "811c61a3b56418e037ec55d93061c6113eb213f650c4a9f2f735d2a390f6423e242b6574bca90907e8330add05555d19fe560922bfd56cf591ae349a8f3b53bd",
          "sha256": "329ed3e31fe81a8851b3523bbe44739852121ec2651af632a57f0aedbb53afec",
          "sha1": "36d370b7e6018d75b61c685f84cd1a152424042e",
          "md5": "dfd93773ef79ea7dee6e6fb4a4ce32f2"
        }
      ]
    }
  ]
}
