{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "ui-calling",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-calling-1.1.1.aar",
          "url": "ui-calling-1.1.1.aar",
          "size": 78155,
          "sha512": "3054a26d78072e6d090835d529ae1d5f8056f3340164aba7f5390672ff1ea6f327d6bbf1999a0e6d294de6a72d9a939b4675714eeb242e4f90dd7caf73a61572",
          "sha256": "97e22b8b306038d7c24c8f15dbeade07c7853e6338c730b0acf4cc619cda5e39",
          "sha1": "06f2ae863be243fe33aad0900f1a8514243ad8d1",
          "md5": "8eeef38e7772a3606eaff57824b6b975"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-calling-1.1.1.aar",
          "url": "ui-calling-1.1.1.aar",
          "size": 78155,
          "sha512": "3054a26d78072e6d090835d529ae1d5f8056f3340164aba7f5390672ff1ea6f327d6bbf1999a0e6d294de6a72d9a939b4675714eeb242e4f90dd7caf73a61572",
          "sha256": "97e22b8b306038d7c24c8f15dbeade07c7853e6338c730b0acf4cc619cda5e39",
          "sha1": "06f2ae863be243fe33aad0900f1a8514243ad8d1",
          "md5": "8eeef38e7772a3606eaff57824b6b975"
        }
      ]
    }
  ]
}
