{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "ui-smartcamera",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-smartcamera-1.1.1.aar",
          "url": "ui-smartcamera-1.1.1.aar",
          "size": 598495,
          "sha512": "aacacb10a56f95f408b27a246914440ef70cd49cb3efd1c65c071ddf8479afbe652734a25bc6041766feb4fd31d4392115ba5012563cf4612284b106a0c8d26b",
          "sha256": "a19b70843c5d07e417da26c5f7af6ff803b727916a39bdf4d07a881e7f4cbac9",
          "sha1": "85ce3182d6366bda6cc56ad615754174a560fb63",
          "md5": "cddd55dfcb1ddba46ea3884790e2bf14"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-smartcamera-1.1.1.aar",
          "url": "ui-smartcamera-1.1.1.aar",
          "size": 598495,
          "sha512": "aacacb10a56f95f408b27a246914440ef70cd49cb3efd1c65c071ddf8479afbe652734a25bc6041766feb4fd31d4392115ba5012563cf4612284b106a0c8d26b",
          "sha256": "a19b70843c5d07e417da26c5f7af6ff803b727916a39bdf4d07a881e7f4cbac9",
          "sha1": "85ce3182d6366bda6cc56ad615754174a560fb63",
          "md5": "cddd55dfcb1ddba46ea3884790e2bf14"
        }
      ]
    }
  ]
}
