{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "smartcamera-editor",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "context",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartcamera-editor-1.3.0.aar",
          "url": "smartcamera-editor-1.3.0.aar",
          "size": 7101,
          "sha512": "a9b410f58c46ce399f20ad0c72bc67b11b49123078e1f0292985eda1cf0186aa9e63072cf27afc87b4efd9362627c82c2ba803027a8b15a602a99a72a789d2fe",
          "sha256": "5f5e62ab17af83b4d125f494b59b30fe37ab2caa9c501ef2d215f18b92192056",
          "sha1": "c8b3605d4be6ac46ddef7117ef2609fed5b3c852",
          "md5": "9b3d5ec6ec6df2e64f8d1b1faba66197"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "context",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "smartcamera-editor-1.3.0.aar",
          "url": "smartcamera-editor-1.3.0.aar",
          "size": 7101,
          "sha512": "a9b410f58c46ce399f20ad0c72bc67b11b49123078e1f0292985eda1cf0186aa9e63072cf27afc87b4efd9362627c82c2ba803027a8b15a602a99a72a789d2fe",
          "sha256": "5f5e62ab17af83b4d125f494b59b30fe37ab2caa9c501ef2d215f18b92192056",
          "sha1": "c8b3605d4be6ac46ddef7117ef2609fed5b3c852",
          "md5": "9b3d5ec6ec6df2e64f8d1b1faba66197"
        }
      ]
    }
  ]
}
