{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "fbns",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fbns-1.3.0.aar",
          "url": "fbns-1.3.0.aar",
          "size": 20098,
          "sha512": "afda01132d6f7e824a3ecf5ee4ade00dee6de788d9cf3c321b831fcc6ce3d0c66df7121e396d9bbe7b8dbe658a12cafb7c329588807f29daccae2b5879a34558",
          "sha256": "8f52b08dfcbce8f7df784e6a6314575743a7f980b8308016589da1a8e63e9613",
          "sha1": "b645f09dd6e757c79fc264d51c5c3e1983c13565",
          "md5": "54568268bd436aa3ef7f0a5bff1628c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "fbns-1.3.0.aar",
          "url": "fbns-1.3.0.aar",
          "size": 20098,
          "sha512": "afda01132d6f7e824a3ecf5ee4ade00dee6de788d9cf3c321b831fcc6ce3d0c66df7121e396d9bbe7b8dbe658a12cafb7c329588807f29daccae2b5879a34558",
          "sha256": "8f52b08dfcbce8f7df784e6a6314575743a7f980b8308016589da1a8e63e9613",
          "sha1": "b645f09dd6e757c79fc264d51c5c3e1983c13565",
          "md5": "54568268bd436aa3ef7f0a5bff1628c6"
        }
      ]
    }
  ]
}
