{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "calling-ipc",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "calling-ipc-1.3.0.aar",
          "url": "calling-ipc-1.3.0.aar",
          "size": 29479,
          "sha512": "96cbc6bba66ad4c6abade830dd98fa9f44165e0463412e1f30c9bfa4ad88fb96fad51750643d021e9bba50b3e1f7fd93b8b5ee241f74c6e42e452077d89c744f",
          "sha256": "da5ed7072ea89eec2040becedcc1a4b7fa8a49208c4398d5d93cd34144bbe1eb",
          "sha1": "b0908e3ac72f7ccc6ab6cbf9d4d367d2bcf54fa4",
          "md5": "fa21925f667d3a7f25f5e362702251d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "calling-ipc-1.3.0.aar",
          "url": "calling-ipc-1.3.0.aar",
          "size": 29479,
          "sha512": "96cbc6bba66ad4c6abade830dd98fa9f44165e0463412e1f30c9bfa4ad88fb96fad51750643d021e9bba50b3e1f7fd93b8b5ee241f74c6e42e452077d89c744f",
          "sha256": "da5ed7072ea89eec2040becedcc1a4b7fa8a49208c4398d5d93cd34144bbe1eb",
          "sha1": "b0908e3ac72f7ccc6ab6cbf9d4d367d2bcf54fa4",
          "md5": "fa21925f667d3a7f25f5e362702251d9"
        }
      ]
    }
  ]
}
