{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "calling",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "call-notification",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "calling-client",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "calling-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "ui-calling",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "calling-1.3.0.aar",
          "url": "calling-1.3.0.aar",
          "size": 53652,
          "sha512": "01eb15b5229ee96f9761691a776b11b9d33146efc8ac73c80d475d017b940ead0f0af1671cce74d36d15058bd3aa6bcc836e3643f5a2a9ab7d0ac394e83d9fdb",
          "sha256": "c08d2bb6be63121042935eab8e9030df217813df8bd4bd4747e4be144eede101",
          "sha1": "112cc11e356a5955bdcb50b3876b18b9e2960d56",
          "md5": "2c854adfb14e3c6041c118b6501bbf53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "call-notification",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "calling-client",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "calling-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "ui-calling",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "calling-1.3.0.aar",
          "url": "calling-1.3.0.aar",
          "size": 53652,
          "sha512": "01eb15b5229ee96f9761691a776b11b9d33146efc8ac73c80d475d017b940ead0f0af1671cce74d36d15058bd3aa6bcc836e3643f5a2a9ab7d0ac394e83d9fdb",
          "sha256": "c08d2bb6be63121042935eab8e9030df217813df8bd4bd4747e4be144eede101",
          "sha1": "112cc11e356a5955bdcb50b3876b18b9e2960d56",
          "md5": "2c854adfb14e3c6041c118b6501bbf53"
        }
      ]
    }
  ]
}
