{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "systemstate",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-1.3.0.aar",
          "url": "systemstate-1.3.0.aar",
          "size": 6827,
          "sha512": "60917f0586c11f149980f771224f038740f871218fb49a773dd6397d6aea52b5c7262a26105cbc5a66a41e17dba3458fd383b1565bb483927cbe144ac7893a58",
          "sha256": "caf03572c2f3699d69074b21c6c5c0e094791dcdf8304b21fbfc8148c4a1b833",
          "sha1": "25915a4eb9a18cb6417851f00b4ee3e886fc6ce4",
          "md5": "55fb7bfbad7f8b6da7e4df2c52efa3d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-1.3.0.aar",
          "url": "systemstate-1.3.0.aar",
          "size": 6827,
          "sha512": "60917f0586c11f149980f771224f038740f871218fb49a773dd6397d6aea52b5c7262a26105cbc5a66a41e17dba3458fd383b1565bb483927cbe144ac7893a58",
          "sha256": "caf03572c2f3699d69074b21c6c5c0e094791dcdf8304b21fbfc8148c4a1b833",
          "sha1": "25915a4eb9a18cb6417851f00b4ee3e886fc6ce4",
          "md5": "55fb7bfbad7f8b6da7e4df2c52efa3d8"
        }
      ]
    }
  ]
}
