{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "systemstate-ipc",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-ipc-1.3.0.aar",
          "url": "systemstate-ipc-1.3.0.aar",
          "size": 10456,
          "sha512": "920f1c1840b175b4602150c524dc2389b4b14ae63ce19026d8ed702548bb76a8b7e03121c5fb41db0d535120c7b5f3bd40f66f258eb0dd0b0101ce651e7a1329",
          "sha256": "b7f8fa7be17d4c2f2aea6d1acb5a5de5d98ec808205ccd0b758ead0240b6bffb",
          "sha1": "160aa013d50e55e34637a6d351ab9df28a6c6a7a",
          "md5": "b389f438646d38558abe3a79c6d4096d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-ipc-1.3.0.aar",
          "url": "systemstate-ipc-1.3.0.aar",
          "size": 10456,
          "sha512": "920f1c1840b175b4602150c524dc2389b4b14ae63ce19026d8ed702548bb76a8b7e03121c5fb41db0d535120c7b5f3bd40f66f258eb0dd0b0101ce651e7a1329",
          "sha256": "b7f8fa7be17d4c2f2aea6d1acb5a5de5d98ec808205ccd0b758ead0240b6bffb",
          "sha1": "160aa013d50e55e34637a6d351ab9df28a6c6a7a",
          "md5": "b389f438646d38558abe3a79c6d4096d"
        }
      ]
    }
  ]
}
