{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "context",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "context-1.1.1.aar",
          "url": "context-1.1.1.aar",
          "size": 20145,
          "sha512": "da7af68246472c8860a493bb3ee19268cffed37a641cd2497d673d2dfcbd2b94b03eb9c4493ae04d9eeb9e5f93fe5e27808a715bfc437e891a3c7ca613021a40",
          "sha256": "7ec0414b0eb426f1e32623058f285425fd5933f8c9f291c21c2ad0a7749636eb",
          "sha1": "3f9c7aee3f06d8c4165f942ba6ad65f024e0528c",
          "md5": "e60b4e5c925c8d35a7f085f02a3199a1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "context-1.1.1.aar",
          "url": "context-1.1.1.aar",
          "size": 20145,
          "sha512": "da7af68246472c8860a493bb3ee19268cffed37a641cd2497d673d2dfcbd2b94b03eb9c4493ae04d9eeb9e5f93fe5e27808a715bfc437e891a3c7ca613021a40",
          "sha256": "7ec0414b0eb426f1e32623058f285425fd5933f8c9f291c21c2ad0a7749636eb",
          "sha1": "3f9c7aee3f06d8c4165f942ba6ad65f024e0528c",
          "md5": "e60b4e5c925c8d35a7f085f02a3199a1"
        }
      ]
    }
  ]
}
