{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "smartcamera",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "smartcamera-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "smartcamera-1.3.0.aar",
          "url": "smartcamera-1.3.0.aar",
          "size": 88347,
          "sha512": "2f1dcb0c9a1689a1f14b25b11649702dccced38b5cfd8cf4334815b0c106570c3e2c0778abe52f82cb4242c421b32ee0cda0ab795a7d510d156d7b3d9a51020c",
          "sha256": "d65d3ccc6580b7429afdbe11f1e052ecce4a9601ab8d6d6d5671d99bf0d7b19d",
          "sha1": "1202a93b05e2c165bb1ed4a155bf5569c4bc054e",
          "md5": "ac14f1e5b703c8edaaadfd9319e6da9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "smartcamera-ipc",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "smartcamera-1.3.0.aar",
          "url": "smartcamera-1.3.0.aar",
          "size": 88347,
          "sha512": "2f1dcb0c9a1689a1f14b25b11649702dccced38b5cfd8cf4334815b0c106570c3e2c0778abe52f82cb4242c421b32ee0cda0ab795a7d510d156d7b3d9a51020c",
          "sha256": "d65d3ccc6580b7429afdbe11f1e052ecce4a9601ab8d6d6d5671d99bf0d7b19d",
          "sha1": "1202a93b05e2c165bb1ed4a155bf5569c4bc054e",
          "md5": "ac14f1e5b703c8edaaadfd9319e6da9c"
        }
      ]
    }
  ]
}
