{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "ui",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "smartcamera-editor",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.1.1.aar",
          "url": "ui-1.1.1.aar",
          "size": 207024,
          "sha512": "4e7d7f5dbc0dbbd08ae3d29ffd5da470c5b4e7f76e0474f5b7361c493f236a803a74340dea5dcc21dc50f9505af2e8567fb119b65b0e9436a01eafb54dab1b47",
          "sha256": "34be795e6ac487670d679523590740e00827fec14c203d115cda3f817aa61599",
          "sha1": "069dac5cd2a008864e08d610ecc743fd400cad32",
          "md5": "d45a6f82fd7576b5d4fd146c9d3ea0a1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "smartcamera-editor",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.1.1.aar",
          "url": "ui-1.1.1.aar",
          "size": 207024,
          "sha512": "4e7d7f5dbc0dbbd08ae3d29ffd5da470c5b4e7f76e0474f5b7361c493f236a803a74340dea5dcc21dc50f9505af2e8567fb119b65b0e9436a01eafb54dab1b47",
          "sha256": "34be795e6ac487670d679523590740e00827fec14c203d115cda3f817aa61599",
          "sha1": "069dac5cd2a008864e08d610ecc743fd400cad32",
          "md5": "d45a6f82fd7576b5d4fd146c9d3ea0a1"
        }
      ]
    }
  ]
}
