{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "ui",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "smartcamera-editor",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.3.0.aar",
          "url": "ui-1.3.0.aar",
          "size": 196430,
          "sha512": "ec21c26cef7a35bf8a16f307c61d4628a8f24b5a115a0256159a855f38ae8b047d177f57df1acffe59d1d3b0fedf307d02b47a4c9ed09be4c5f5164649104c6a",
          "sha256": "99966ff874b8bb1ddc829ce4663760b09ff3aa7563225105cbf2e348b96635c6",
          "sha1": "c4e6e50f79c243fdb459bdef6452d2cacba99fc1",
          "md5": "c0aac127fb2d4c03f617f0ab7929805a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "smartcamera-editor",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.3.0.aar",
          "url": "ui-1.3.0.aar",
          "size": 196430,
          "sha512": "ec21c26cef7a35bf8a16f307c61d4628a8f24b5a115a0256159a855f38ae8b047d177f57df1acffe59d1d3b0fedf307d02b47a4c9ed09be4c5f5164649104c6a",
          "sha256": "99966ff874b8bb1ddc829ce4663760b09ff3aa7563225105cbf2e348b96635c6",
          "sha1": "c4e6e50f79c243fdb459bdef6452d2cacba99fc1",
          "md5": "c0aac127fb2d4c03f617f0ab7929805a"
        }
      ]
    }
  ]
}
