{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "call-notification",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "call-notification-1.3.0.aar",
          "url": "call-notification-1.3.0.aar",
          "size": 29574,
          "sha512": "3c58872997d9d10c1eb2d080a76b6918a376a5f4369754e02f7e91eba31cbe2f73d1a4777a4860bcf953c2b48f8fcbba9895b61d0db8029de19af98f0b0d003f",
          "sha256": "d73750642a7fee7e1068f777fdd47898cccbf4ef15702a3f5d066c8e2a3e847b",
          "sha1": "42a0443d2ddfbab6f0ac421464edc9e1c5b27af1",
          "md5": "3007e0e465621fafa227506debdba439"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "call-notification-1.3.0.aar",
          "url": "call-notification-1.3.0.aar",
          "size": 29574,
          "sha512": "3c58872997d9d10c1eb2d080a76b6918a376a5f4369754e02f7e91eba31cbe2f73d1a4777a4860bcf953c2b48f8fcbba9895b61d0db8029de19af98f0b0d003f",
          "sha256": "d73750642a7fee7e1068f777fdd47898cccbf4ef15702a3f5d066c8e2a3e847b",
          "sha1": "42a0443d2ddfbab6f0ac421464edc9e1c5b27af1",
          "md5": "3007e0e465621fafa227506debdba439"
        }
      ]
    }
  ]
}
