{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "systemstate-ipc",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-ipc-1.1.1.aar",
          "url": "systemstate-ipc-1.1.1.aar",
          "size": 10333,
          "sha512": "d533c7d418d99b999239f9f65730ac511f7eefed7fd43889560d11a988c61f7c61535cc0183a3edc0fcd859d1556df9c9ef23df08163e535a08411a8fc1514a9",
          "sha256": "b05c44cc3ae95220d60d4a2e037e1a69844db4b47997e97f14544ff32198662b",
          "sha1": "ed865400d4fb3795f0fe04813ac34a7d58526c36",
          "md5": "98e1e87728839c3aa50ba38ed6d54c9c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-ipc-1.1.1.aar",
          "url": "systemstate-ipc-1.1.1.aar",
          "size": 10333,
          "sha512": "d533c7d418d99b999239f9f65730ac511f7eefed7fd43889560d11a988c61f7c61535cc0183a3edc0fcd859d1556df9c9ef23df08163e535a08411a8fc1514a9",
          "sha256": "b05c44cc3ae95220d60d4a2e037e1a69844db4b47997e97f14544ff32198662b",
          "sha1": "ed865400d4fb3795f0fe04813ac34a7d58526c36",
          "md5": "98e1e87728839c3aa50ba38ed6d54c9c"
        }
      ]
    }
  ]
}
