{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "systemstate",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate-ipc",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-1.1.1.aar",
          "url": "systemstate-1.1.1.aar",
          "size": 6826,
          "sha512": "2b3c16c215f6beb654f68a4e00289fbff6ec06e714591e75cbdbb2d83ae5be0e566a2dd887814c188f6e35b32f2270545f916d4ff3e3e026107745fe21342e20",
          "sha256": "26dfd2864a2306133eebba6923570c13dfbe03ab2922da4b9c255e8cc170be61",
          "sha1": "6b7676e2934d2526317a372028d563f98e469c37",
          "md5": "297f6683d92c2b99be9b68691d9a30de"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.facebook.portal",
          "module": "systemstate-ipc",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "systemstate-1.1.1.aar",
          "url": "systemstate-1.1.1.aar",
          "size": 6826,
          "sha512": "2b3c16c215f6beb654f68a4e00289fbff6ec06e714591e75cbdbb2d83ae5be0e566a2dd887814c188f6e35b32f2270545f916d4ff3e3e026107745fe21342e20",
          "sha256": "26dfd2864a2306133eebba6923570c13dfbe03ab2922da4b9c255e8cc170be61",
          "sha1": "6b7676e2934d2526317a372028d563f98e469c37",
          "md5": "297f6683d92c2b99be9b68691d9a30de"
        }
      ]
    }
  ]
}
