{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "context",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "context-1.3.0.aar",
          "url": "context-1.3.0.aar",
          "size": 21261,
          "sha512": "ca5f4c2c97f96a90a43ec9aad60e26a3d515da0b2b700ee70ce5b42b5fac561bd5e24f6cd8fefcb3b9711865a97b10f4cea6b33459b27604fc67f6f271cac84e",
          "sha256": "d18e6614e55eb4468f432eb1aaeeb3ce551b420a8e5bad53d945bb3fddb4fe8e",
          "sha1": "20d7503cd4f705927184b715d86a1504d330ec57",
          "md5": "574f0264ae14b4c0667b6da94b562415"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "context-1.3.0.aar",
          "url": "context-1.3.0.aar",
          "size": 21261,
          "sha512": "ca5f4c2c97f96a90a43ec9aad60e26a3d515da0b2b700ee70ce5b42b5fac561bd5e24f6cd8fefcb3b9711865a97b10f4cea6b33459b27604fc67f6f271cac84e",
          "sha256": "d18e6614e55eb4468f432eb1aaeeb3ce551b420a8e5bad53d945bb3fddb4fe8e",
          "sha1": "20d7503cd4f705927184b715d86a1504d330ec57",
          "md5": "574f0264ae14b4c0667b6da94b562415"
        }
      ]
    }
  ]
}
