{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "ui-calling",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-calling-1.3.0.aar",
          "url": "ui-calling-1.3.0.aar",
          "size": 77352,
          "sha512": "e26cd89418208d39781184e37ccf9d237ee459a30738bc9739c21cadd9ca90f4036ef74095098e3d23aea8c2ee98691197e59e4564095897ee2db382638978de",
          "sha256": "025eb7492d1f6ba73361598b8c68adaca598f75426036e64fe245edab48389e3",
          "sha1": "2aca42d09d7dee9040855be793ef89394b8e3f3d",
          "md5": "8acafc3d89167620756b68cfc310c569"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-calling-1.3.0.aar",
          "url": "ui-calling-1.3.0.aar",
          "size": 77352,
          "sha512": "e26cd89418208d39781184e37ccf9d237ee459a30738bc9739c21cadd9ca90f4036ef74095098e3d23aea8c2ee98691197e59e4564095897ee2db382638978de",
          "sha256": "025eb7492d1f6ba73361598b8c68adaca598f75426036e64fe245edab48389e3",
          "sha1": "2aca42d09d7dee9040855be793ef89394b8e3f3d",
          "md5": "8acafc3d89167620756b68cfc310c569"
        }
      ]
    }
  ]
}
