{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.portal",
    "module": "call-notification",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "call-notification-1.1.1.aar",
          "url": "call-notification-1.1.1.aar",
          "size": 27073,
          "sha512": "2fe644d8a9a53fb40d150a4da87d011df80a0dcbd02de7faa8bc890599ea5c60e780b1c1e9434f824d291970c855914796fa56d5e9b2910c35d25dc16e22b69c",
          "sha256": "d285d5ee8e043ae8312111fe4a6f713544a758b4ab38cebd5caf17918ec764c1",
          "sha1": "094a615ca4a4f4021cc7c0903067c52ff3905a8b",
          "md5": "f7415ba66abc39ec5cfe7e72a7fb7062"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.portal",
          "module": "base",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.microg",
          "module": "safe-parcel",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "call-notification-1.1.1.aar",
          "url": "call-notification-1.1.1.aar",
          "size": 27073,
          "sha512": "2fe644d8a9a53fb40d150a4da87d011df80a0dcbd02de7faa8bc890599ea5c60e780b1c1e9434f824d291970c855914796fa56d5e9b2910c35d25dc16e22b69c",
          "sha256": "d285d5ee8e043ae8312111fe4a6f713544a758b4ab38cebd5caf17918ec764c1",
          "sha1": "094a615ca4a4f4021cc7c0903067c52ff3905a8b",
          "md5": "f7415ba66abc39ec5cfe7e72a7fb7062"
        }
      ]
    }
  ]
}
